-- DATA PREPARATION AND UNDERSTANDING

--ANS.1 START--

SELECT COUNT(*) AS CUSTOMER_ROWS FROM CUSTOMER 
SELECT COUNT(*) AS  TRANS_ROWS FROM TRANSACTIONS
SELECT COUNT(*) AS PROD_INFO_ROWS FROM PROD_CAT_INFO 


--ANS.1 END 

--ANS.2 START

SELECT COUNT(TRANSACTION_ID) AS TOTAL_TRANS FROM TRANSACTIONS
WHERE QTY < 0


--ANS.2 END


--ANS.3 START


SELECT CONVERT(DATE, DOB, 103) AS DATES FROM CUSTOMER 
SELECT CONVERT(DATE, TRAN_DATE, 103) FROM TRANSACTIONS
 

--ANS.3 END

--ANS .4 


SELECT DATEDIFF(DAY, MIN(CONVERT(DATE, TRAN_DATE, 103)), MAX(CONVERT(DATE, TRAN_DATE, 103))) as [Day], 
DATEDIFF(MONTH, MIN(CONVERT(DATE, TRAN_DATE, 103)), MAX(CONVERT(DATE, TRAN_DATE, 103))) as [Month],  
DATEDIFF(YEAR, MIN(CONVERT(DATE, TRAN_DATE, 103)), MAX(CONVERT(DATE, TRAN_DATE, 103))) as [Year]
FROM TRANSACTIONS


--ANS.4 END


--ANS.5 START


SELECT PROD_CAT FROM PROD_CAT_INFO
WHERE PROD_SUBCAT = 'DIY'



--ANS.5 END






        --DATA ANALYSIS



  
--ANS1. START


SELECT TOP 1 STORE_TYPE, COUNT(TRANSACTION_ID) AS TOTAL FROM TRANSACTIONS
GROUP BY  STORE_TYPE
ORDER BY COUNT(TRANSACTION_ID) DESC



--ANS.1 END



--ANS.2 START

SELECT GENDER ,COUNT(GENDER) AS [COUNT] FROM CUSTOMER
WHERE GENDER IN ('M' ,'F')
GROUP BY GENDER


--ANS.2 END 





--ANS.3 START 

 SELECT TOP 1 CITY_CODE , COUNT(CUSTOMER_ID) AS TOTAL FROM CUSTOMER
 GROUP BY CITY_CODE
 ORDER BY COUNT(CUSTOMER_ID) DESC


 --ANS.3 END 




 --ANS.4 START
 

 SELECT COUNT(PROD_SUBCAT)  AS  TOTAL FROM PROD_CAT_INFO
 WHERE PROD_CAT = 'BOOKS'


--ANS.4 END




--ANS.5 START


SELECT MAX(QTY) AS [MAX_QUNT] FROM TRANSACTIONS 


--ANS.5 END



--ANS.6 START



 SELECT  PROD_CAT ,SUM(TOTAL_AMT) AS TOTAL FROM TRANSACTIONS
 INNER JOIN PROD_CAT_INFO ON PROD_CAT_INFO.PROD_CAT_CODE= TRANSACTIONS.PROD_CAT_CODE
 WHERE PROD_CAT IN ('ELECTRONICS' ,'BOOKS')
 GROUP BY PROD_CAT


--ANS.6 END 



--ANS.7 START


SELECT CUST_ID , COUNT(TRANSACTION_ID) AS TOTAL FROM TRANSACTIONS
WHERE QTY > 0
GROUP BY CUST_ID
HAVING  COUNT(TRANSACTION_ID) > 10


--ANS.7 END



--ANS.8 START



SELECT SUM(TOTAL_AMT) AS TOTAL_REVENUE FROM TRANSACTIONS
INNER JOIN PROD_CAT_INFO ON PROD_CAT_INFO.PROD_CAT_CODE = TRANSACTIONS.PROD_CAT_CODE
WHERE PROD_CAT IN ('ELECTRONICS' , 'CLOTHING') AND  STORE_TYPE = 'FLAGSHIP STORE'


--ANS.8 END 


--ANS.9 START



SELECT PROD_SUBCAT , SUM(TOTAL_AMT) AS TOTAL FROM TRANSACTIONS
INNER JOIN PROD_CAT_INFO ON PROD_CAT_INFO.PROD_CAT_CODE=TRANSACTIONS.PROD_CAT_CODE
INNER JOIN CUSTOMER ON CUSTOMER.CUSTOMER_ID=TRANSACTIONS.CUST_ID
WHERE GENDER='M' AND  PROD_CAT= 'ELECTRONICS'
GROUP BY PROD_SUBCAT


--ANS.9 END



--ANS.10 START



SELECT TOP 5 PROD_SUBCAT, (SUM(TOTAL_AMT) / (SELECT SUM(TOTAL_AMT) FROM TRANSACTIONS)) * 100 AS [PERCENTAGE]
FROM TRANSACTIONS
INNER JOIN PROD_CAT_INFO ON PROD_CAT_INFO.PROD_CAT_CODE = TRANSACTIONS.PROD_CAT_CODE
GROUP BY PROD_SUBCAT
ORDER BY SUM(TOTAL_AMT) DESC



--ANS.10 END



--ANS.11 START



SELECT t.CUST_ID, SUM(t.TOTAL_AMT) AS REVENUE
FROM TRANSACTIONS t
INNER JOIN CUSTOMER c ON t.CUST_ID = c.CUSTOMER_ID
WHERE DATEDIFF(YEAR, CONVERT(DATE, c.DOB, 103), GETDATE()) BETWEEN 25 AND 35
 AND CONVERT(DATE, t.TRAN_DATE, 103) BETWEEN
 DATEADD(DAY, -30, (SELECT MAX(CONVERT(DATE, TRAN_DATE, 103)) FROM TRANSACTIONS))
 AND (SELECT MAX(CONVERT(DATE, TRAN_DATE, 103)) FROM TRANSACTIONS)
GROUP BY t.CUST_ID;



--ANS.11 END



--ANS.12 START





SELECT TOP 1 PROD_CAT, SUM(T.TOTAL_AMT) AS [VALUE]
FROM TRANSACTIONS T
INNER JOIN PROD_CAT_INFO ON PROD_CAT_INFO.PROD_CAT_CODE = T.PROD_CAT_CODE
WHERE T.TOTAL_AMT < 0
  AND CONVERT(DATE, T.TRAN_DATE, 103) BETWEEN
    DATEADD(MONTH, -3, (SELECT MAX(CONVERT(DATE, TRAN_DATE, 103)) FROM TRANSACTIONS))
    AND (SELECT MAX(CONVERT(DATE, TRAN_DATE, 103)) FROM TRANSACTIONS)
GROUP BY PROD_CAT
ORDER BY 2 DESC;



--ANS.12 END


--ANS.13 START
 


SELECT TOP 1 STORE_TYPE  , SUM(TOTAL_AMT) AS TOTAL_AMT , SUM(QTY) AS QTY FROM TRANSACTIONS
GROUP BY STORE_TYPE
ORDER BY SUM(TOTAL_AMT) , QTY DESC



--ANS.13 END


--ANS.14 START




SELECT PROD_CAT, AVG(TOTAL_AMT) AS AVERAGE
FROM TRANSACTIONS
INNER JOIN PROD_CAT_INFO ON PROD_CAT_INFO.PROD_CAT_CODE=TRANSACTIONS.PROD_CAT_CODE
GROUP BY PROD_CAT
HAVING AVG(TOTAL_AMT)> (SELECT AVG(TOTAL_AMT) FROM TRANSACTIONS) 




--ANS.14 END




--ANS.15 START 



SELECT PROD_SUBCAT ,SUM(TOTAL_AMT) AS REVENUE , AVG(TOTAL_AMT) AS AVGE  FROM TRANSACTIONS
INNER JOIN PROD_CAT_INFO ON PROD_CAT_INFO.PROD_CAT_CODE=TRANSACTIONS.PROD_CAT_CODE
WHERE PROD_CAT IN (SELECT TOP 5 PROD_CAT FROM TRANSACTIONS
                  INNER JOIN PROD_CAT_INFO ON PROD_CAT_INFO.PROD_CAT_CODE=TRANSACTIONS.PROD_CAT_CODE
                   GROUP BY PROD_CAT
				   ORDER BY SUM(QTY) DESC)
GROUP BY  PROD_SUBCAT , TOTAL_AMT 
ORDER BY REVENUE DESC




--ANS.15 END